## What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

## In other terms

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python. It is open-source software.

In [ ]:
from IPython.display import Image
Image(filename='numpy.png')

#### In this image you can see the axis role for numpy which is extremely important for working with.

Numpy is used for some important tasks such as, reading, writing, resizing, slicing images and etc.<br>
Also it is used in working with structured data with the help of the pandas.

### Let's learn how should we use Numpy

In [2]:
import numpy as np

#### one dimensional array

In [ ]:
array = np.array([1, 2, 3])
print(array)

In [ ]:
type(array)

In [ ]:
array = np.array([1.1, 2, 3], dtype=float)
print(array)

In [ ]:
array = np.array([1, 2, 3], dtype=str)
print(array)

In [ ]:
len(array)

In [ ]:
max(array)

In [ ]:
min(array)

In [ ]:
sum(array)

In [ ]:
for index in array:
    print(index)

#### two dimensional array

In [ ]:
array_2 = np.array([[1, 2, 3], 
                    [4, 5, 6]])
print(array_2)

In [ ]:
min(array_2)

In [ ]:
max(array_2)

In [ ]:
len(array_2)

In [ ]:
sum(array_2)

In [ ]:
array.ndim

In [ ]:
array_2.ndim

In [ ]:
array_new = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])
print(array_new)

In [ ]:
len(array_new)

In [ ]:
array_new.ndim

In [ ]:
array_3 = np.array([[[1, 2], [3, 4], [5, 6]],
                [[7, 8], [9, 10], [11, 12]]])
print(array_3)
print(array_3.shape)

In [ ]:
len(array_3)

In [ ]:
array_3.ndim

#### Tip: in imagining an array it will be much easier to move reverse form deeper dimension to shallow one. for example in two dimention first column after that row or in three dimention first depth second column and last row.

#### Tip: the best way to find the dimension of the array is the number of brackets in the starting of the array [ [ [

In [ ]:
# with using shape method we can see the number of rows, columns and depth respectivly
array_3.shape

In [ ]:
# building some famous array
zero = np.zeros((2, 3))
print(zero)

In [ ]:
one = np.ones((2, 3))
print(one)

In [ ]:
# [start-end) arange gramer
arange = np.arange(10)
print(arange)

In [ ]:
arange = np.arange(2, 10)
print(arange)

In [ ]:
arange = np.arange(2, 10, 2)
print(arange)

In [ ]:
# [start slice between end] linspace gramer
lin = np.linspace(10, 20)
print(lin)

In [ ]:
lin = np.linspace(10, 20, 5)
print(lin)

In [ ]:
full = np.full((3, 7), 2)
print(full)

In [ ]:
eye = np.eye(6)
print(eye)

In [ ]:
random = np.random.random((3, 7))
print(random)

In [ ]:
# saving an array
np.save('random_array.npy', random)

In [ ]:
# loading an array
random_copy = np.load('random_array.npy')

In [ ]:
print(random_copy)

In [ ]:
# saving multi_array
np.savez('multi_array.npz', random, full)

In [ ]:
multi_copy = np.load('multi_array.npz')
print(multi_copy)

In [ ]:
# we can use multi array with special gramer
# [arr_t] is the gramer
print(multi_copy['arr_0'])

In [ ]:
print(multi_copy['arr_1'])

In [ ]:
# describing a numpy array
print(full)

In [ ]:
full.shape

In [ ]:
len(full)

In [ ]:
full.ndim

In [ ]:
full.size

In [ ]:
full.dtype

In [ ]:
full = full.astype(np.float64)
print(full.dtype)
print(full)

In [ ]:
array_complex = np.array([1, 2, 3], dtype = complex)
print(array_complex)

In [ ]:
tf_array = np.array([[0, 1, 0],
                     [1, 0, 1],
                     [1, 1, 1],
                     [0, 0, 0]], dtype = bool)
print(tf_array)

#### math oprations in Numpy

In [ ]:
arr_1 = np.array([[5, -1],
                  [3, 2]])

arr_2 = np.array([[-5, 1],
                  [-3, -2]])

In [ ]:
print(arr_1)
print()
print(arr_2)

In [ ]:
print(arr_1+arr_2)
print()
print(arr_1-arr_2)
print()
print(arr_1*arr_2)
print()
print(arr_1/arr_2)

In [ ]:
# e** evry element in arr_1
np.exp(arr_1)

In [ ]:
np.sqrt(arr_1)

In [ ]:
np.sin(arr_1)

In [ ]:
np.cos(arr_1)

In [ ]:
np.log(arr_1)

In [ ]:
# this is a matrix multiply
print(np.matmul(arr_1, arr_2))

In [ ]:
arr_1@arr_2

In [ ]:
arr_3 = np.array([[5, -1, 3],
                  [3, 2, 7]])

arr_4 = np.array([[-5, 1],
                  [-3, -2],
                  [6, 1]])

In [ ]:
print(np.matmul(arr_3, arr_4))

In [ ]:
print(np.matmul(arr_4, arr_3))

In [ ]:
arr_4@arr_3

In [ ]:
arr_3@arr_4

#### equality in Numpy 

In [3]:
a = np.array([1, 3, 5])
b = np.array([1, 2, 4])
print(a == b)

[ True False False]


In [4]:
np.array_equal(a, b)

False

In [5]:
np.array_equal(a, a)

True

In [6]:
print(a < 3)

[ True False False]


In [7]:
print(b > 3)

[False False  True]


#### some statistic oprator in Numpy

In [ ]:
print(arr_3)

In [ ]:
print(np.sum(arr_3))

In [ ]:
print(np.sum(arr_3, axis=0))

In [ ]:
print(np.min(arr_3))

In [ ]:
print(np.max(arr_3))

In [ ]:
print(np.max(arr_3, axis=1))

In [ ]:
print(np.mean(arr_3))

In [ ]:
print(np.median(arr_3))

In [ ]:
print(np.std(arr_3))

#### slicing in Numpy

In [8]:
test_arr = np.array([4, 1, 3, 2, 5, 6])

In [9]:
copy_arr = test_arr.copy()

In [10]:
test_arr[3] = 23

In [11]:
test_arr

array([ 4,  1,  3, 23,  5,  6])

In [12]:
copy_arr

array([4, 1, 3, 2, 5, 6])

In [13]:
np.sort(test_arr)

array([ 1,  3,  4,  5,  6, 23])

In [14]:
test_arr_2 = np.array([[4 , 3],
                       [1 , 5]])

In [15]:
np.sort(test_arr_2, axis = 0)

array([[1, 3],
       [4, 5]])

In [16]:
np.sort(test_arr_2, axis = 1)

array([[3, 4],
       [1, 5]])

In [17]:
test_arr = np.array([4, 1, 3, 2, 5, 6])

In [18]:
test_arr[-1]

6

In [19]:
big_array = np.array([[2, 4, 6, 8],
                      [1, 3, 5, 7], 
                      [20, 10, 9, 50]])

In [20]:
big_array[0]

array([2, 4, 6, 8])

In [21]:
big_array[0, 2]

6

In [22]:
test_arr = np.array([4, 1, 3, 2, 5, 6])

big_array = np.array([[2, 4, 6, 8],
                      [1, 3, 5, 7], 
                      [20, 10, 9, 50]])

In [23]:
print(test_arr[1:4])

[1 3 2]


In [24]:
print(big_array[1:3])

[[ 1  3  5  7]
 [20 10  9 50]]


In [25]:
# row:row , col:col
print(big_array[1:3, 1:3])

[[ 3  5]
 [10  9]]


In [26]:
print(test_arr[::-1])

[6 5 2 3 1 4]


In [27]:
print(big_array[::-1])

[[20 10  9 50]
 [ 1  3  5  7]
 [ 2  4  6  8]]


In [28]:
print(big_array[::-1, ::-1])

[[50  9 10 20]
 [ 7  5  3  1]
 [ 8  6  4  2]]


In [29]:
big_array = np.array([[2, 4, 6, 8],
                      [1, 3, 5, 7], 
                      [20, 10, 9, 50]])

In [30]:
np.transpose(big_array)

array([[ 2,  1, 20],
       [ 4,  3, 10],
       [ 6,  5,  9],
       [ 8,  7, 50]])

In [31]:
big_array.T

array([[ 2,  1, 20],
       [ 4,  3, 10],
       [ 6,  5,  9],
       [ 8,  7, 50]])

In [32]:
test_arr = np.array([4, 1, 3, 2, 5, 6])

In [33]:
arr_3 = np.array([[5, -1, 3],
                  [3, 2, 7]])

arr_4 = np.array([[-5, 1],
                  [-3, -2],
                  [6, 1]])

In [34]:
test_arr[[True, False, False, False, True, True]]

array([4, 5, 6])

In [35]:
test_arr[test_arr > 3]

array([4, 5, 6])

In [36]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [37]:
arr_3 = np.array([[5, -1],
                  [3, 2], 
                 [5, 7]])

arr_4 = np.array([[-5, 1],
                  [-3, -2],
                  [6, 1]])

In [39]:
re_array = arr_3.reshape(2, 3)
print(re_array)

[[ 5 -1  3]
 [ 2  5  7]]


In [41]:
re_array1 = arr_3.reshape(6, 1)
print(re_array1)

[[ 5]
 [-1]
 [ 3]
 [ 2]
 [ 5]
 [ 7]]


In [40]:
re_array1 = arr_3.reshape(6,)
print(re_array1)

[ 5 -1  3  2  5  7]


In [47]:
re_array2 = arr_3.reshape(6, -1)
print(re_array2)

[[ 5]
 [-1]
 [ 3]
 [ 2]
 [ 5]
 [ 7]]


In [45]:
re_array2 = arr_3.reshape(-1, 2)
print(re_array2)

[[ 5 -1]
 [ 3  2]
 [ 5  7]]


In [50]:
print(arr_3)
print('\n')
print(arr_4)

[[ 5 -1]
 [ 3  2]
 [ 5  7]]


[[-5  1]
 [-3 -2]
 [ 6  1]]


In [51]:
c_mat = np.concatenate((arr_3, arr_4), axis = 0)
print(c_mat)

[[ 5 -1]
 [ 3  2]
 [ 5  7]
 [-5  1]
 [-3 -2]
 [ 6  1]]


In [52]:
stack_v = np.vstack((arr_3, arr_4))
print(stack_v)

[[ 5 -1]
 [ 3  2]
 [ 5  7]
 [-5  1]
 [-3 -2]
 [ 6  1]]


In [53]:
stack_h = np.hstack((arr_3, arr_4))
print(stack_h)

[[ 5 -1 -5  1]
 [ 3  2 -3 -2]
 [ 5  7  6  1]]


In [54]:
print(help(np.where))

Help on function where in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x an

In [55]:
M = np.array([[10, 0, 11, -1, 12],
             [0, 13, 0, 14, -4],
             [6, 5, 15, 1, 0],
             [4, 20, 7, -3, -30],
             [1, 1, 1, 10, 0]])

In [56]:
new_M = np.where(M > 0, M)
print(new_M)

ValueError: either both or neither of x and y should be given

In [58]:
new_M = np.where(M > 0, M, 0)
print(new_M)

[[10  0 11  0 12]
 [ 0 13  0 14  0]
 [ 6  5 15  1  0]
 [ 4 20  7  0  0]
 [ 1  1  1 10  0]]


In [59]:
new_M = np.where(M > 0, M, M*M)
print(new_M)

[[ 10   0  11   1  12]
 [  0  13   0  14  16]
 [  6   5  15   1   0]
 [  4  20   7   9 900]
 [  1   1   1  10   0]]


## Exercise 1

Extract the third column of the matrix M

## Exercise 2

Extract only the odd-index rows and columns, i.e. those with indices 1, 3, .. of M

## Exercise 3

Extract the positive values of the matrix M

## Exercise 4

Replace all negative values of matrix M with 0