#### Pandas is a powerful and open-source Python library. The Pandas library is used for data manipulation and analysis. Pandas consists of data structures and functions to perform efficient operations on data.
#### pandas supports all format such as csv, json, sql, xlsx and etc.

In [1]:
import pandas as pd

#### In pandas we have two important data types :
1. Series: This count as 1-dimensional dataset
2. Dataframe: This one count as multi-dimensional dataset

In [2]:
from IPython.display import Image
Image(filename='pandas_image.png')

FileNotFoundError: [Errno 2] No such file or directory: 'pandas_image.png'

### Series

In [3]:
dict_1 = {'armin': 24, 'arta': 18, 'soorena': 19, 'alhan': 19, 'parsa': 16}

In [4]:
print(pd.Series(dict_1))

armin      24
arta       18
soorena    19
alhan      19
parsa      16
dtype: int64


In [5]:
lst = [24, 18, 19, 19, 16]

In [6]:
print(pd.Series(lst))

0    24
1    18
2    19
3    19
4    16
dtype: int64


In [7]:
print(pd.Series(lst, index = ['armin', 'arta', 'soorena', 'alhan', 'parsa']))

armin      24
arta       18
soorena    19
alhan      19
parsa      16
dtype: int64


In [8]:
series_1 = pd.Series(lst, index = ['armin', 'arta', 'soorena', 'alhan', 'parsa'])

In [9]:
dict_1 = {'armin': 24, 'arta': 18, 'soorena': 19, 'alhan': 19, 'parsa': 16}

In [10]:
print(dict_1.keys())
print(dict_1.values())

dict_keys(['armin', 'arta', 'soorena', 'alhan', 'parsa'])
dict_values([24, 18, 19, 19, 16])


In [11]:
print(series_1.index)
print(series_1.values)

Index(['armin', 'arta', 'soorena', 'alhan', 'parsa'], dtype='object')
[24 18 19 19 16]


In [12]:
# Dictionary
dict_1['armin']

24

In [13]:
# Series
print(series_1['armin'])
print(series_1.armin)
print(series_1[0])

24
24
24


C:\Users\AG\AppData\Local\Temp\ipykernel_14536\3473172433.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series_1[0])


In [14]:
print(dict_1['armin', 'soorena'])

KeyError: ('armin', 'soorena')

In [15]:
print(series_1[['armin', 'soorena']])

armin      24
soorena    19
dtype: int64


In [16]:
print(series_1[[0, 2]])

armin      24
soorena    19
dtype: int64


C:\Users\AG\AppData\Local\Temp\ipykernel_14536\1357822494.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series_1[[0, 2]])


In [17]:
print(series_1[0:3])

armin      24
arta       18
soorena    19
dtype: int64


In [18]:
print(series_1['armin': 'soorena'])

armin      24
arta       18
soorena    19
dtype: int64


In [19]:
print(series_1[[True, True, False, False, True]])

armin    24
arta     18
parsa    16
dtype: int64


#### Series Oprations

In [20]:
print(series_1.mean())

19.2


In [21]:
print(series_1 > series_1.mean())

armin       True
arta       False
soorena    False
alhan      False
parsa      False
dtype: bool


In [22]:
print(series_1[series_1 > series_1.mean()])

armin    24
dtype: int64


#### This is the capability of Series.

#### Now let's work with DataFrame

In [2]:
scores = {'Math':[12, 14, 16, 18, 20], 'Programming':[1, 2, 3, 4, 5], 'Physics':[13.5, 15.5, 17.5, 20, 10]}

In [3]:
df = pd.DataFrame(scores)
print(df)

   Math  Programming  Physics
0    12            1     13.5
1    14            2     15.5
2    16            3     17.5
3    18            4     20.0
4    20            5     10.0


In [4]:
df.shape

(5, 3)

In [5]:
# finding rows & cols 
print(df.columns)

Index(['Math', 'Programming', 'Physics'], dtype='object')


In [6]:
print(df.index)

RangeIndex(start=0, stop=5, step=1)


In [7]:
print(df.values)

[[12.   1.  13.5]
 [14.   2.  15.5]
 [16.   3.  17.5]
 [18.   4.  20. ]
 [20.   5.  10. ]]


In [8]:
import numpy as np
dataset = np.array(df.values)
print(dataset)

[[12.   1.  13.5]
 [14.   2.  15.5]
 [16.   3.  17.5]
 [18.   4.  20. ]
 [20.   5.  10. ]]


In [9]:
dataset = dataset.reshape(3, -1)
print(dataset)

[[12.   1.  13.5 14.   2. ]
 [15.5 16.   3.  17.5 18. ]
 [ 4.  20.  20.   5.  10. ]]


#### Some methods for describing DataFrames

In [10]:
print(df)

   Math  Programming  Physics
0    12            1     13.5
1    14            2     15.5
2    16            3     17.5
3    18            4     20.0
4    20            5     10.0


In [11]:
df.head(2)

Math  Programming  Physics
0    12            1     13.5
1    14            2     15.5

In [12]:
df.tail(2)

Math  Programming  Physics
3    18            4     20.0
4    20            5     10.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Math         5 non-null      int64  
 1   Programming  5 non-null      int64  
 2   Physics      5 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 252.0 bytes


In [14]:
df.describe()

Math  Programming    Physics
count   5.000000     5.000000   5.000000
mean   16.000000     3.000000  15.300000
std     3.162278     1.581139   3.817722
min    12.000000     1.000000  10.000000
25%    14.000000     2.000000  13.500000
50%    16.000000     3.000000  15.500000
75%    18.000000     4.000000  17.500000
max    20.000000     5.000000  20.000000

#### Working with element of dataframe

In [15]:
# This is a series
df['Math']

0    12
1    14
2    16
3    18
4    20
Name: Math, dtype: int64

In [16]:
df.Math

0    12
1    14
2    16
3    18
4    20
Name: Math, dtype: int64

In [17]:
df["Math"] > 14

0    False
1    False
2     True
3     True
4     True
Name: Math, dtype: bool

#### Let's get familiar with loc & iloc

In [18]:
# iloc method
print(df)

   Math  Programming  Physics
0    12            1     13.5
1    14            2     15.5
2    16            3     17.5
3    18            4     20.0
4    20            5     10.0


In [19]:
print(df.iloc[2, 2])

17.5


In [20]:
print(df.iloc[1:4, 0:3])

   Math  Programming  Physics
1    14            2     15.5
2    16            3     17.5
3    18            4     20.0


In [22]:
print(df.iloc[[1, 4], 1:])

   Programming  Physics
1            2     15.5
4            5     10.0


In [24]:
print(df.iloc[[True, False, True, False, True], [0, 2]])

   Math  Physics
0    12     13.5
2    16     17.5
4    20     10.0


In [25]:
# loc method
print(df)

   Math  Programming  Physics
0    12            1     13.5
1    14            2     15.5
2    16            3     17.5
3    18            4     20.0
4    20            5     10.0


In [26]:
print(df.loc[3, 'Programming'])

4


In [27]:
print(df.loc[1:4, "Math":"Physics"])

   Math  Programming  Physics
1    14            2     15.5
2    16            3     17.5
3    18            4     20.0
4    20            5     10.0


#### Attention: loc is a label based mathod so, its gramer is : [start, end]

In [28]:
print(df.loc[[1, 3, 4], ['Math', 'Physics']])

   Math  Physics
1    14     15.5
3    18     20.0
4    20     10.0


In [29]:
print(df.loc[[True, True, False, False, False], ["Programming", "Physics"]])

   Programming  Physics
0            1     13.5
1            2     15.5


#### Working with data using pandas 

In [ ]:
import pandas as pd

In [ ]:
iris_data = pd.read_csv('iris_1.csv')

In [ ]:
print(iris_data)

In [ ]:
iris_data = pd.read_csv('iris_1.csv', sep = '\t')

In [ ]:
print(iris_data)

In [ ]:
iris_data = pd.read_csv('iris_1.csv', header = None, 
                        names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'])

In [ ]:
print(iris_data)

In [ ]:
iris_data.head()

In [ ]:
iris_data.tail()

In [ ]:
iris_data.info()

In [ ]:
iris_data.describe()

In [ ]:
iris_features = iris_data.iloc[: , :-1]

In [ ]:
print(iris_features)

In [ ]:
iris_labels = iris_data.iloc[: , -1:]

In [ ]:
print(iris_labels)

In [ ]:
data_iris = pd.read_csv('iris_2.csv')

In [ ]:
data_iris = pd.read_csv('iris_2.csv', header = None, 
                        names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'],
                       skiprows = 2)

In [ ]:
data_iris

In [ ]:
data_iris_2 = pd.read_csv('iris_3.csv', header = None, 
                        names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'],
                       skiprows = 2)

In [ ]:
print(data_iris_2)

In [ ]:
data_iris_2 = pd.read_csv('iris_3.csv', header = None, 
                        names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'],
                       skiprows = 2,
                         comment = '#')

In [ ]:
print(data_iris_2)

In [ ]:
data_iris_3 = pd.read_csv('iris_3.csv', header = None, 
                        names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'],
                       skiprows = 2,
                         comment = '#', 
                         usecols = ['sepal_length', 'petal_length'])

In [ ]:
print(data_iris_3)